# Generated by Django 6.0.7 on 2026-07-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The Daily National Times', max_length=200)),
                ('logo', models.URLField(blank=True, default='https://blogger.googleusercontent.com/img/a/AVvXsEgfNjTco0DS8LPt5dif0d1AcQnZa3O1QlTr3tFg9AIRZBUMnSVVaMZFGBX76xbMNrn4e_BkWQ5inC8CiEyl_yJQzUBgZ03JUg4tfUHZlLwoOiork6s1ATXdkOhCiky0aZ6h3uY8CckSHf_RWDpPVq9UrWUVwU3sHFBXUqKOsoeHNBh1UxBUqboW9Z8Xyd2k=s720', max_length=500)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('copyright_text', models.CharField(blank=True, default='© Copyright: The Daily National Times | Editor & Publisher: Samir Talukdar', max_length=300)),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/', max_length=300)),
                ('twitter', models.URLField(blank=True, default='https://x.com/', max_length=300)),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/', max_length=300)),
                ('youtube', models.URLField(blank=True, default='https://youtube.com/', max_length=300)),
                ('telegram', models.URLField(blank=True, default='https://telegram.me/', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
