# Generated by Django 6.0.7 on 2026-07-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slot', models.CharField(choices=[('home_top', 'Home Top Banner'), ('home_mid', 'Home Middle'), ('sidebar', 'Sidebar'), ('article_bottom', 'Article Bottom'), ('footer', 'Footer')], default='sidebar', max_length=30)),
                ('image_url', models.URLField(blank=True, max_length=600)),
                ('link', models.URLField(blank=True, max_length=600)),
                ('html', models.TextField(blank=True, help_text='Raw ad HTML (e.g. AdSense snippet). Used when set.')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['slot', 'order'],
            },
        ),
    ]
